"""
FileName: Distinct powers
Author: N.G 1.4.21
Purpose: Find how many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100
"""


LIMIT = 100


def main():
    distinct_sequence = set()
    for a in range(2, LIMIT + 1):
        for b in range(2, LIMIT + 1):
            distinct_sequence.add(a ** b)
    print(len(distinct_sequence))


if __name__ == "__main__":
    main()
